"""Render the experiment report (reports/<experiment>.md) from gathered records.

Pure: takes ExperimentData (and optional operator notes), returns markdown text. One
section per DMAIC phase, each with its tollgate verdict, then Limits.
"""

from __future__ import annotations

import json
from typing import Any, Callable, Iterable, Mapping, Sequence

from ..contracts.common import CHECK_IDS
from ..contracts.paths import load_cycle
from .data import SET_ORDER, ArmData, ExperimentData, dpo_counts, verdicts

PHASES = ("define", "measure", "analyze", "improve", "control")
CHECK_NAMES = {c.id: c.name for c in load_cycle().ctqs}

TOKEN_NOTE = (
    "Token counts come from the provider's usage reports. `input` includes prompt-cache writes "
    "(the runner's model client counts cache writes as input, see `adaptive_harness/runner/models.py`); "
    "`cache read` is input served from the prompt cache and is not included in `input`."
)
PRICE_NOTE = "No per-token prices were supplied by the operator, so no dollar cost is reported; tokens are reported per model."


# ---------------------------------------------------------------- formatting helpers


def table(header: Sequence[str], rows: Iterable[Sequence[Any]], align: Sequence[str] | None = None) -> str:
    align = align or ["---"] * len(header)
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(align) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(_cell(c) for c in row) + " |")
    return "\n".join(lines)


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def rate(defects: int, opportunities: int) -> str:
    """DPO with its counts beside it."""
    if not opportunities:
        return f"n/a ({defects}/0)"
    return f"{defects / opportunities:.3f} ({defects}/{opportunities})"


def n(value: float | int) -> str:
    return f"{int(round(value)):,}"


def secs(value: float) -> str:
    return f"{value:,.1f}"


def verdict_line(phase: Mapping[str, Any]) -> str:
    status = phase.get("status", "not_reached")
    tg = phase.get("tollgate") or {}
    if status == "not_reached":
        return "**Tollgate: not reached.** The cycle stopped before this phase."
    word = "PASSED" if tg.get("passed") else "DID NOT PASS"
    reasons = "; ".join(tg.get("reasons", [])) or "no reasons recorded"
    return f"**Tollgate: {word}** ({status}). {reasons}."


def excerpt(content: Any, width: int = 700) -> str:
    text = content if isinstance(content, str) else json.dumps(content, ensure_ascii=False, sort_keys=True, default=str)
    text = " ".join(text.split())
    return text if len(text) <= width else text[: width - 3] + "..."


def arm_label(a: ArmData) -> str:
    return f"{a.arm} ({'/'.join(a.versions)} on {a.snapshot})"


# ---------------------------------------------------------------- sections


def header(d: ExperimentData) -> str:
    exp = d.experiment
    lines = [
        f"# Experiment {exp['_id']}: DMAIC report",
        "",
        "Generated by `python -m adaptive_harness report` from the MongoDB records of this experiment "
        "(runs, events, evaluations, harness_versions, lessons, experiments). Nothing here is written by hand.",
        "",
        f"- Decision: **{exp.get('decision') or 'none yet'}**"
        + (f" (candidate {exp['candidate_version']})" if exp.get("candidate_version") else ""),
        f"- Where the cycle stopped: {stopped_at(d)}",
        f"- Cases: " + ", ".join(f"{c} ({d.case_sets[c]})" for c in d.cases),
        f"- Arms, in the order they ran: " + ", ".join(arm_label(a) for a in d.arms.values()),
    ]
    for vid, v in sorted(d.versions.items()):
        lines.append(f"- Version {vid}: status {v.get('status')}, pinned {v.get('pinned')}, "
                     f"config hash `{v.get('config_hash')}`")
    lines += ["", "Run ids by arm:", ""]
    lines.append(table(["arm", "case", "run id", "status"],
                       [(a.arm, c, r["_id"], r.get("status")) for a in d.arms.values()
                        for c in d.cases if (r := a.runs.get(c))]))
    return "\n".join(lines)


def stopped_at(d: ExperimentData) -> str:
    dm = d.experiment.get("dmaic") or {}
    for p in PHASES:
        ph = dm.get(p) or {}
        if ph.get("status") == "stopped":
            reasons = "; ".join((ph.get("tollgate") or {}).get("reasons", []))
            return f"{p} (tollgate did not pass: {reasons})"
        if ph.get("status", "not_reached") == "not_reached":
            return f"before {p} (not reached)"
    return "did not stop: every tollgate passed"


def define_section(d: ExperimentData, notes: Mapping[str, str]) -> str:
    ph = (d.experiment.get("dmaic") or {}).get("define") or {}
    art = ph.get("artifact") or {}
    ch = art.get("charter") or {}
    out = ["## Define", "", verdict_line(ph), ""]
    if notes.get("define"):
        out += ["### Case set", "", notes["define"], ""]
    if not ch:
        return "\n".join(out)
    b = ch.get("baseline", {})
    out += [
        "### Charter",
        "",
        f"- Evidence: {', '.join(ch.get('evidence', []))} cases only ({', '.join(ch.get('cases', []))}).",
        f"- Baseline ({b.get('arm')} arm, {b.get('runs')} runs): {rate(b.get('defects', 0), b.get('opportunities', 0))} "
        f"defects per opportunity; failure categories {json.dumps(b.get('failure_categories', {}))}.",
        "",
        "Critical-to-quality characteristics with defects:",
        "",
        table(["check", "name", "statement", "failure category", "DPO (defects/opps)"],
              [(c["id"], c["name"], c["statement"], c["failure_category"], rate(c["defects"], c["opportunities"]))
               for c in ch.get("ctqs", [])]),
        "",
        "Scope (the editable surfaces):",
        "",
        table(["cause", "surface", "description"], [(s["cause"], f"`{s['surface']}`", s["description"])
                                                    for s in ch.get("scope", [])]),
        "",
        f"Out of scope: {', '.join(ch.get('out_of_scope', []))}.",
        "",
        "Goal (the acceptance rules):",
        "",
        *[f"- {g}" for g in ch.get("goal", [])],
        "",
        "### Problem statement",
        "",
        f"> {art.get('problem_statement', '(none)')}",
    ]
    return "\n".join(out)


def measure_section(d: ExperimentData) -> str:
    ph = (d.experiment.get("dmaic") or {}).get("measure") or {}
    art = ph.get("artifact") or {}
    out = ["## Measure", "", verdict_line(ph), ""]
    if art:
        h = art.get("hashes", {})
        out += [
            "### Measurement checks",
            "",
            f"- Evaluator SHA-256: {', '.join(f'`{x}`' for x in h.get('evaluator_sha256', []))}",
            f"- Answer-key SHA-256: {', '.join(f'`{x}`' for x in h.get('key_sha256', []))} (matches `data/key.sha256`)",
            f"- HARNESS reruns made by the measure phase: {len(art.get('harness_reruns', []))}",
            "",
            "Re-score of every baseline run in a fresh evaluator process:",
            "",
            table(["run id", "identical verdicts", "evaluator hash match", "key hash match", "differing checks"],
                  [(r["run_id"], r["identical"], r["evaluator_sha256_match"], r["key_sha256_match"],
                    ", ".join(r.get("differing_checks", [])) or "none") for r in art.get("rescore", [])]),
            "",
        ]
        rep = art.get("repeat")
        if rep:
            changed = rep.get("changed_checks") or []
            out += ["### Repeat of the development cases", "",
                    f"The development cases ran once more under {rep.get('version')} on {rep.get('snapshot')} "
                    f"(arm repeat) and were compared check by check with the baseline: "
                    f"{rep.get('cases_compared', 0)} case(s) compared; checks that changed between the identical "
                    f"runs: {', '.join(map(str, changed)) if changed else 'none'}.", ""]
            by_id = rep.get("checks_changed_by_id") or {}
            if by_id:
                out.append(table(["check", *by_id], [("changes", *by_id.values())]))
                out.append("")
    out += harness_section(d)
    arms = list(d.arms.values())
    out += ["### Defects per opportunity by arm", "",
            "Each cell is DPO with (defects/opportunities). HARNESS and NA are neither.", ""]
    out.append(table(["arm", "runs", "DPO"],
                     [(arm_label(a), len(a.runs), rate(*dpo_counts(list(a.evaluations.values())))) for a in arms]))
    out += ["", "### By check", ""]
    out.append(table(["check", "name", *[a.arm for a in arms]],
                     [(cid, CHECK_NAMES.get(cid, ""), *[rate(*check_counts(a, cid)) for a in arms]) for cid in CHECK_IDS]))
    out += ["", "### By case set", ""]
    out.append(table(["case set", *[a.arm for a in arms]],
                     [(s, *[rate(*dpo_counts([e for c, e in a.evaluations.items() if d.case_sets.get(c) == s]))
                            for a in arms]) for s in SET_ORDER]))
    out += ["", "### Pareto table of defects by check", ""]
    for a in arms:
        rows = pareto(a)
        out += [f"{arm_label(a)}:", ""]
        out.append(table(["check", "name", "defects", "share", "cumulative share"], rows) if rows else "No defects.")
        out.append("")
    if art.get("cost_per_run"):
        cpr = art["cost_per_run"]
        out += ["### Cost per baseline run", "", TOKEN_NOTE, ""]
        out.append(table(["run id", "case", "model calls", "tool calls", "input", "output", "cache read", "wall s"],
                         [(r["run_id"], r["case_id"], r["model_calls"], r["tool_calls"], n(r["input_tokens"]),
                           n(r["output_tokens"]), n(r["cache_read_tokens"]), secs(r["wall_seconds"]))
                          for r in cpr.get("per_run", [])]))
        m = cpr.get("mean", {})
        if m:
            out.append(f"| mean | | {m['model_calls']:.1f} | {m['tool_calls']:.1f} | {n(m['input_tokens'])} | "
                       f"{n(m['output_tokens'])} | {n(m['cache_read_tokens'])} | {secs(m['wall_seconds'])} |")
    out += ["", "No sigma level or capability index is reported (see Limits)."]
    return "\n".join(out)


def harness_section(d: ExperimentData) -> list[str]:
    """Runs that ended HARNESS (measurement-system failures), their cause, and the rerun scored instead."""
    rows = []
    for a in d.arms.values():
        for r in a.all_runs:
            if r["_id"] not in d.harness_errors:
                continue
            errs = [e for e in d.harness_errors[r["_id"]]
                    if isinstance(e.get("content"), dict) and e["content"].get("status") == "harness_error"]
            errs = errs or d.harness_errors[r["_id"]][-1:]
            cause = excerpt((errs[-1].get("content") or {}).get("message") if errs else "no error event recorded", 220)
            scored = a.runs.get(r["case_id"])
            replaced = scored["_id"] if scored and scored["_id"] != r["_id"] else "none"
            rows.append((a.arm, r["case_id"], r["_id"], cause, replaced))
    if not rows:
        return []
    return ["### HARNESS results", "",
            "Measurement-system failures: neither defects nor opportunities. Each case was rerun once and the "
            "rerun is the run scored.", "",
            table(["arm", "case", "run id", "cause (recorded error)", "rerun scored"], rows), ""]


def check_counts(a: ArmData, cid: str) -> tuple[int, int]:
    defects = opps = 0
    for e in a.evaluations.values():
        r = verdicts(e)[cid]
        if r in ("PASS", "FAIL"):
            opps += 1
            defects += r == "FAIL"
    return defects, opps


def passed_in_set(d: ExperimentData, a: ArmData, case_set: str) -> int:
    return sum(list(verdicts(e).values()).count("PASS")
               for c, e in a.evaluations.items() if d.case_sets.get(c) == case_set)


def pareto(a: ArmData) -> list[tuple[Any, ...]]:
    counts = [(cid, check_counts(a, cid)[0]) for cid in CHECK_IDS]
    counts = sorted([c for c in counts if c[1]], key=lambda c: (-c[1], c[0]))
    total = sum(c for _, c in counts)
    rows, cum = [], 0
    for cid, k in counts:
        cum += k
        rows.append((cid, CHECK_NAMES.get(cid, ""), k, f"{k / total:.2f}", f"{cum / total:.2f}"))
    return rows


def analyze_section(d: ExperimentData) -> str:
    ph = (d.experiment.get("dmaic") or {}).get("analyze") or {}
    art = ph.get("artifact") or {}
    out = ["## Analyze", "", verdict_line(ph), ""]
    if not art:
        return "\n".join(out)
    out.append(f"Development defects analyzed: {art.get('defects', 0)}; verified: {len(art.get('verified', []))}; "
               f"verified and controllable: {len(art.get('verified_controllable', []))}; "
               f"provisional (never retrieved): {len(art.get('provisional', []))}. Lessons written to snapshot "
               f"{art.get('snapshot')}.")
    lessons = {l["_id"]: l for l in d.lessons}
    for rc in art.get("root_causes", []):
        l = lessons.get(rc.get("lesson_id"), {})
        dfx = rc.get("defect", {})
        out += ["", f"### Root cause `{rc.get('lesson_id')}`", "",
                f"- Defect: {dfx.get('check_id')} ({dfx.get('category')}) on case {dfx.get('case_id')}, "
                f"run `{dfx.get('run_id')}`",
                f"- Cause category: **{rc.get('cause_category')}** (controllable: {rc.get('controllable')}); "
                f"status {rc.get('status')}",
                ]
        if rc.get("problems"):
            out.append(f"- Verification problems: {'; '.join(rc['problems'])}")
        if l:
            out += ["", "Why-chain:", ""]
            out += [f"{i}. {w}" for i, w in enumerate(l.get("why_chain", []), 1)]
            origin = d.events.get(l.get("origin_event_id"))
            out += ["", f"Origin event `{l.get('origin_event_id')}`"
                    + (f" ({origin.get('stage_id') or '-'} {origin.get('role') or 'code'} {origin.get('type')}):"
                       if origin else " (not found in the store):")]
            if origin:
                out += ["", "```", excerpt(origin.get("content")), "```"]
            out += ["", f"Source events: {', '.join(f'`{e}`' for e in l.get('source_event_ids', []))}", "",
                    f"Lesson: {l.get('text')}"]
    return "\n".join(out)


def improve_section(d: ExperimentData) -> str:
    exp = d.experiment
    ph = (exp.get("dmaic") or {}).get("improve") or {}
    art = ph.get("artifact") or {}
    out = ["## Improve", "", verdict_line(ph), ""]
    if not art:
        return "\n".join(out)
    prop = art.get("proposal") or {}
    val = art.get("validation") or {}
    history = [h for h in art.get("history") or [] if isinstance(h, str)]
    if "history" in art:
        out += ["### Proposal history shown to the improvement agent", ""]
        if history:
            out.append(table(["version", "status", "changes", "decision reasons"],
                             [(vid, (d.versions.get(vid) or {}).get("status"),
                               "; ".join(f"{c['op']['op']} `{c['op']['path']}` = {json.dumps(c['op'].get('value'))}"
                                         for c in (d.versions.get(vid) or {}).get("changes", [])),
                               "; ".join((d.versions.get(vid) or {}).get("decision_reasons", [])))
                              for vid in history]))
            out += ["", "The agent sees each earlier change set with its development-case outcome only; the "
                    "validator refuses an exact repeat of a rejected change set.", ""]
        else:
            out += ["None: no earlier proposal existed.", ""]
    out += ["### Proposal", "", f"Candidate {art.get('candidate_version')} from {art.get('from')}, "
            f"lesson retrieval: {art.get('retrieval')}.", ""]
    out.append(table(["op", "path", "value", "cites root cause", "why"],
                     [(c["op"]["op"], f"`{c['op']['path']}`", json.dumps(c["op"].get("value")), f"`{c['lesson_id']}`",
                       c["why"]) for c in prop.get("changes", [])]))
    out += ["", f"- Rationale: {prop.get('rationale', '')}", f"- Expected effect: {prop.get('expected_effect', '')}",
            f"- Risks: {prop.get('risks', '')}", "",
            f"**Validator verdict:** {'valid' if val.get('valid') else 'invalid'}"
            + (f" ({'; '.join(val.get('reasons', []))})" if val.get("reasons") else " (no problems)") + ".", ""]

    arms = list(d.arms.values())
    out += ["### Checks by case and arm", "",
            "One row per case and check; one column per arm. NA rows (check not applicable in every arm) are omitted.",
            ""]
    rows = []
    for c in d.cases:
        for cid in CHECK_IDS:
            cells = [verdicts(a.evaluations.get(c))[cid] if c in a.runs else "-" for a in arms]
            if all(x in ("NA", "-") for x in cells):
                continue
            changed = " ◆" if len({x for x in cells if x not in ("-",)}) > 1 else ""
            rows.append((c, d.case_sets.get(c), f"{cid} {CHECK_NAMES.get(cid, '')}{changed}", *cells))
    out.append(table(["case", "set", "check", *[arm_label(a) for a in arms]], rows))
    out += ["", "◆ marks a check whose verdict differs between arms.", "", "Checks passed per case set:", ""]
    out.append(table(["case set", *[a.arm for a in arms]],
                     [(s, *[passed_in_set(d, a, s) for a in arms]) for s in SET_ORDER]))

    acc = exp.get("acceptance") or (art.get("acceptance") or {})
    out += ["", "### Acceptance rules", ""]
    if acc:
        out.append(table(["rule", "holds", "detail"],
                         [(r, "yes" if acc[r]["holds"] else "**no**", acc[r]["detail"]) for r in sorted(acc)]))
        out += ["", f"Decision: **{exp.get('decision')}**."]
    else:
        out.append("Not applied yet (the pilot arms have not been verified).")

    out += ["", "### Cost per arm", "", TOKEN_NOTE, "", PRICE_NOTE, ""]
    out.append(table(["arm", "runs", "model calls", "tool calls", "input", "output", "cache read", "wall s"],
                     [(arm_label(a), len(a.runs), n(a.totals.get("model_calls", 0)), n(a.totals.get("tool_calls", 0)),
                       n(a.totals.get("input_tokens", 0)), n(a.totals.get("output_tokens", 0)),
                       n(a.totals.get("cache_read_tokens", 0)), secs(a.totals.get("wall_seconds", 0.0)))
                      for a in arms]))
    out += ["", "Split by the model that answered (from the model_call events):", ""]
    out.append(table(["arm", "model", "model calls", "input", "output", "cache read"],
                     [(a.arm, m, n(u["model_calls"]), n(u["input_tokens"]), n(u["output_tokens"]),
                       n(u["cache_read_tokens"])) for a in arms for m, u in a.usage_by_model.items()]))
    agent_rows = []
    for p in PHASES:
        a = ((exp.get("dmaic") or {}).get(p) or {}).get("artifact") or {}
        agents = [a["agent"]] if isinstance(a.get("agent"), dict) else []
        agents += [rc["agent"] for rc in a.get("root_causes", [])
                   if isinstance(rc, dict) and isinstance(rc.get("agent"), dict)]
        for g in agents:
            u = g.get("usage", {})
            agent_rows.append((p, g.get("model"), n(u.get("input_tokens", 0)), n(u.get("output_tokens", 0)),
                               n(u.get("cache_read_tokens", 0))))
    if agent_rows:
        out += ["", "Improvement-agent calls (outside the arms):", ""]
        out.append(table(["phase", "model", "input", "output", "cache read"], agent_rows))
    return "\n".join(out)


def control_section(d: ExperimentData, xychart_ok: bool | None) -> str:
    exp = d.experiment
    ph = (exp.get("dmaic") or {}).get("control") or {}
    pinned = next((v for v in d.versions.values() if v.get("pinned")), None)
    out = ["## Control", "", verdict_line(ph), ""]
    if pinned:
        out.append(f"- Pinned version: **{pinned['_id']}**, config hash `{pinned['config_hash']}`.")
    plan = (pinned or {}).get("control_plan")
    if plan and ph.get("status") != "not_reached":
        out.append(f"- Control plan status: {plan.get('status')}.")
        out += ["", "Thresholds (checks passed per case in the pilot):", ""]
        out.append(table(["case", "threshold"], sorted(plan.get("thresholds", {}).items())))
        out += ["", f"- Reaction plan: {plan.get('reaction_plan')}"]
        conf = plan.get("confirmation_run_ids") or []
        out.append(f"- Confirmation: {', '.join(conf) if conf else 'not run'}.")
        if plan.get("signals"):
            out += ["", table(["run", "case", "passed", "threshold", "repeated"],
                              [(s["run_id"], s["case_id"], s["passed"], s["threshold"], s["repeated"])
                               for s in plan["signals"]])]
    else:
        rule = load_cycle().control
        out += [
            "- Thresholds: none set. The control phase was not reached, so no control plan was armed for a new "
            "version; the pinned version above is unchanged.",
            f"- Reaction plan (as specified, applies once a version is accepted and pinned): a later run that passes "
            f"fewer checks than its case's threshold is a signal; rerun the case {rule.reruns_on_signal} time(s); if "
            f"the signal repeats, pin the parent version and open a new cycle using "
            f"{', '.join(rule.new_cycle_evidence)}-case evidence only. Runs under a different model assignment or "
            f"FastF1 version are flagged, not compared.",
            "- Confirmation: not run.",
        ]
    out += ["", "### Run chart: DPO per arm", "",
            "This is a **run chart**, in the order the arms ran, not a control chart: statistical control limits "
            "need about 20 runs.", ""]
    arms = list(d.arms.values())
    counts = [dpo_counts(list(a.evaluations.values())) for a in arms]
    out.append(table(["order", "arm", "started", "defects", "opportunities", "DPO"],
                     [(i, arm_label(a), str(a.first_started)[:19], k, o, f"{k / o:.3f}" if o else "n/a")
                      for i, (a, (k, o)) in enumerate(zip(arms, counts), 1)]))
    if xychart_ok is not False:
        out += ["", "```mermaid", run_chart_mermaid(d), "```"]
    else:
        out += ["", "(The Mermaid line chart did not render with the installed Mermaid CLI and is omitted.)"]
    return "\n".join(out)


def run_chart_mermaid(d: ExperimentData) -> str:
    arms = list(d.arms.values())
    vals = []
    for a in arms:
        k, o = dpo_counts(list(a.evaluations.values()))
        vals.append(round(k / o, 3) if o else 0)
    top = max([0.1, *vals])
    top = round(top * 1.25 + 0.005, 2)
    xs = ", ".join(f'"{a.arm} {a.snapshot}"' for a in arms)
    return "\n".join([
        "---",
        "config:",
        "  themeVariables:",
        "    xyChart:",
        '      plotColorPalette: "#1f5fbf"',
        "---",
        "xychart-beta",
        f'    title "Run chart: DPO per arm, experiment {d.experiment["_id"]} (not a control chart)"',
        f"    x-axis [{xs}]",
        f'    y-axis "DPO" 0 --> {top}',
        f"    line [{', '.join(str(v) for v in vals)}]",
    ])


def limits_section(d: ExperimentData) -> str:
    n_cases = len(d.case_sets)
    by_set = {s: sum(1 for c in d.case_sets.values() if c == s) for s in SET_ORDER}
    per_arm = {a.arm: len(a.all_runs) for a in d.arms.values()}
    return "\n".join([
        "## Limits",
        "",
        f"- {n_cases} cases ({', '.join(f'{k} {s}' for s, k in by_set.items())}), one run per case per arm "
        f"(runs recorded per arm: {', '.join(f'{a} {k}' for a, k in per_arm.items())}).",
        "- No statistical claim is made: differences between arms are counts from single runs, and the model "
        "is not deterministic, so a repeat could differ.",
        "- No sigma level and no capability index are reported; they need far more opportunities than this "
        "experiment has.",
        "- The run chart is not a control chart; statistical control limits need about 20 runs.",
        "- Evidence rule (configs/cycle.json): only development cases may inform define, analyze, and the "
        "improvement agent's prompts; held-out and control results are used only by code, to verify and control. "
        "The define charter above records which cases it drew on.",
    ])


def render(d: ExperimentData, notes: Mapping[str, str] | None = None, xychart_ok: bool | None = None) -> str:
    notes = notes or {}
    parts = [header(d), define_section(d, notes), measure_section(d), analyze_section(d), improve_section(d),
             control_section(d, xychart_ok), limits_section(d)]
    return "\n\n".join(parts).rstrip() + "\n"
